/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,js,ts,html}', './public/**/*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#6bff8f',
        'inverse-surface': '#2d3133',
        outline: '#737686',
        'on-secondary-fixed': '#001c3b',
        'tertiary-container': '#007e37',
        'on-secondary-container': '#3e5980',
        'primary-fixed-dim': '#b4c5ff',
        'on-surface': '#191c1e',
        'surface-tint': '#0053db',
        'on-secondary': '#ffffff',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e0e3e5',
        secondary: '#455f87',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-on-surface': '#eff1f3',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#004ac6',
        'inverse-primary': '#b4c5ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002109',
        'primary-container': '#2563eb',
        'outline-variant': '#c3c6d7',
        'surface-container': '#eceef0',
        background: '#f7f9fb',
        'tertiary-fixed-dim': '#4ae176',
        'on-primary-fixed': '#00174b',
        'secondary-fixed': '#d5e3ff',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed-variant': '#005321',
        'on-surface-variant': '#434655',
        'secondary-container': '#b5d0fd',
        tertiary: '#006229',
        'on-secondary-fixed-variant': '#2d486d',
        'on-primary-container': '#eeefff',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#adc8f5',
        'on-background': '#191c1e',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-container': '#c1ffc5',
        'primary-fixed': '#dbe1ff',
        'surface-container-highest': '#e0e3e5',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8ea',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        '2xl': '64px',
        xl: '40px',
        md: '16px',
        xs: '4px',
        gutter: '24px',
        lg: '24px',
        sm: '8px',
      },
      fontFamily: {
        display: ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'title-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
      },
    },
  },
};
